import type { CrawlFacts } from '@/lib/crawler/crawl';
import type { Finding, PsiResult, Severity, Status } from '@/types/audit';

const F = (category: string, id: string, title: string, status: Status, severity: Severity, evidence: string, explanation: string, recommendation: string): Finding =>
  ({ id, category, title, status, severity, evidence, explanation, recommendation, source: 'crawler' });
const chk = (category: string, id: string, title: string, ok: boolean, sev: Severity, evOk: string, evBad: string, why: string, fix: string, warn = false): Finding =>
  F(category, id, title, ok ? 'PASS' : warn ? 'WARNING' : 'FAIL', ok ? 'info' : sev, ok ? evOk : evBad, why, ok ? '' : fix);

export function crawlerChecks(c: CrawlFacts): Finding[] {
  const h = c.http.headers, t = c.html.title, d = c.html.metaDescription, im = c.images, out: Finding[] = [];
  const S = 'Security', T = 'Technical SEO', SEO = 'SEO';
  out.push(chk(T, 'http-status', 'Page returns HTTP 200', c.http.status === 200, 'critical', 'HTTP 200', `HTTP ${c.http.status}`, 'Non-200 responses may not be indexed or usable.', 'Serve the page with a 200 status or fix the redirect/error.'));
  out.push(chk(T, 'redirects', 'Redirect chain length', c.http.chain.length <= 2, 'medium', `${c.http.chain.length - 1} redirect(s)`, `${c.http.chain.length - 1} redirects: ${c.http.chain.map((x) => x.status).join(' → ')}`, 'Long redirect chains add latency.', 'Link directly to the final URL and collapse redirects into one hop.', true));
  out.push(chk(T, 'ttfb-crawl', 'Server response time (crawler)', c.http.ms < 1500, 'medium', `${c.http.ms} ms`, `${c.http.ms} ms to fetch HTML (includes redirects)`, 'Slow server responses delay everything else.', 'Use caching/CDN and optimise server-side rendering.', true));
  out.push(chk(T, 'html-content-type', 'Response is HTML', c.http.isHtml, 'high', String(c.http.contentType), `Content-Type: ${c.http.contentType}`, 'Non-HTML responses cannot be audited as web pages.', 'Audit an HTML page URL.'));
  out.push(chk(SEO, 'title', 'Title tag present', !!t, 'high', `"${t}"`, '0 <title> elements with text', 'Titles are the main search result headline.', 'Add a unique, descriptive <title>.'));
  if (t) out.push(chk(SEO, 'title-length', 'Title length 30–60 characters', t.length >= 30 && t.length <= 60, 'low', `${t.length} characters`, `${t.length} characters`, 'Titles outside this range may be truncated or too vague.', 'Rewrite the title to roughly 30–60 characters.', true));
  out.push(chk(SEO, 'meta-desc', 'Meta description present', !!d, 'medium', `${d?.length} characters`, 'No meta description found', 'Descriptions often become the search snippet.', 'Add a unique meta description of 70–160 characters.'));
  if (d) out.push(chk(SEO, 'meta-desc-length', 'Meta description length 70–160', d.length >= 70 && d.length <= 160, 'low', `${d.length} characters`, `${d.length} characters`, 'May be truncated or uninformative.', 'Adjust length to 70–160 characters.', true));
  out.push(chk(SEO, 'h1', 'Exactly one H1', c.html.h1 === 1, c.html.h1 === 0 ? 'high' : 'medium', '1 H1 element', `${c.html.h1} H1 elements detected`, 'A single H1 gives users and crawlers a clear primary heading.', c.html.h1 === 0 ? 'Add one descriptive H1 representing the page purpose.' : 'Keep one H1 and demote the others.', c.html.h1 > 1));
  out.push(chk(SEO, 'noindex', 'Page is indexable', !/noindex/i.test(`${c.html.robotsMeta ?? ''} ${h['x-robots-tag'] ?? ''}`), 'critical', 'No noindex directive', `noindex found (meta: ${c.html.robotsMeta}, header: ${h['x-robots-tag']})`, 'noindex removes the page from search results.', 'Remove noindex if the page should be searchable.'));
  out.push(chk(T, 'canonical', 'Canonical URL declared', !!c.html.canonical, 'medium', c.html.canonical ?? '', 'No rel=canonical found', 'Canonicals consolidate duplicate URLs.', 'Add <link rel="canonical"> pointing to the preferred URL.', true));
  out.push(chk(T, 'lang', 'HTML lang attribute', !!c.html.lang, 'medium', `lang="${c.html.lang}"`, 'No lang attribute on <html>', 'Helps screen readers and search engines pick the language.', 'Add lang, e.g. <html lang="en">.'));
  out.push(chk(T, 'charset', 'Character encoding declared', !!c.html.charset, 'low', String(c.html.charset), 'No charset declared', 'Missing encoding can cause garbled text.', 'Add <meta charset="utf-8">.', true));
  out.push(chk(T, 'robots-txt', 'robots.txt available', c.robotsTxt.available, 'low', 'robots.txt found', 'robots.txt not found or not plain text', 'Crawlers look for crawl rules here.', 'Publish /robots.txt.', true));
  out.push(chk(T, 'sitemap', 'Sitemap referenced in robots.txt', c.robotsTxt.sitemaps.length > 0, 'low', c.robotsTxt.sitemaps[0] ?? '', c.robotsTxt.available ? 'No Sitemap: directive in robots.txt' : 'robots.txt unavailable, sitemap reference unknown', 'Sitemaps help discovery.', 'Add a Sitemap: line to robots.txt.', true));
  out.push(chk(T, 'structured-data', 'Structured data (JSON-LD)', c.structuredData.jsonLdTypes.length > 0, 'low', `Types: ${c.structuredData.jsonLdTypes.join(', ')}`, 'No JSON-LD structured data detected', 'Structured data enables rich results.', 'Add schema.org JSON-LD relevant to the page type.', true));
  if (c.structuredData.invalid) out.push(F(T, 'jsonld-invalid', 'Invalid JSON-LD', 'FAIL', 'medium', `${c.structuredData.invalid} block(s) failed to parse`, 'Invalid JSON-LD is ignored.', 'Validate with the Rich Results Test.'));
  const s = c.social;
  out.push(chk('Social Tags', 'og-basic', 'Open Graph title, description, image', !!(s.ogTitle && s.ogDescription && s.ogImage), 'medium', 'og:title, og:description, og:image present', `Missing: ${[!s.ogTitle && 'og:title', !s.ogDescription && 'og:description', !s.ogImage && 'og:image'].filter(Boolean).join(', ')}`, 'Controls link previews on social platforms.', 'Add the missing Open Graph meta tags.', true));
  out.push(chk('Social Tags', 'twitter-card', 'Twitter/X card', !!s.twCard, 'low', `twitter:card=${s.twCard}`, 'twitter:card missing', 'Controls link previews on X.', 'Add <meta name="twitter:card" content="summary_large_image">.', true));
  if (im.count === 0) ['img-alt', 'img-format', 'img-dims'].forEach((id) => out.push(F('Images', id, id === 'img-alt' ? 'Image alt text' : id === 'img-format' ? 'Modern image formats' : 'Image dimensions', 'NOT_APPLICABLE', 'info', 'No images were detected on the analyzed page.', '', '')));
  else {
    out.push(chk('Images', 'img-alt', 'Images have alt attributes', im.missingAlt === 0, 'high', `${im.count} images, all with alt`, `${im.missingAlt} of ${im.count} images have no alt attribute`, 'Alt text is needed for screen readers and image search.', 'Add descriptive alt text (alt="" for purely decorative images).'));
    out.push(chk('Images', 'img-format', 'Modern image formats (by file extension)', im.legacy === 0 || im.modern > im.legacy, 'medium', `${im.modern} modern, ${im.legacy} legacy`, `${im.legacy} of ${im.count} images use JPEG/PNG/GIF extensions (${im.modern} WebP/AVIF)`, 'WebP/AVIF are usually smaller. Extension-based; CDNs may negotiate formats.', 'Serve WebP/AVIF with fallbacks where supported.', true));
    out.push(chk('Images', 'img-dims', 'Images declare width/height', im.noDimensions === 0, 'medium', 'All images have dimensions', `${im.noDimensions} of ${im.count} images lack width/height`, 'Missing dimensions cause layout shift.', 'Set width and height attributes or CSS aspect-ratio.', true));
  }
  const r = c.resources;
  out.push(chk('Resources', 'js-count', 'External JavaScript files', r.scripts <= 20, 'medium', `${r.scripts} script files`, `${r.scripts} external scripts`, 'Many scripts increase load and parse cost.', 'Bundle, defer and remove unused scripts.', true));
  out.push(chk('Resources', 'third-party', 'Third-party hosts', r.thirdPartyHosts.length <= 8, 'low', `${r.thirdPartyHosts.length} hosts`, `${r.thirdPartyHosts.length} third-party hosts: ${r.thirdPartyHosts.slice(0, 8).join(', ')}`, 'Each host adds DNS/connect cost and risk.', 'Audit and remove unneeded third parties.', true));
  out.push(F('Analytics & Tracking', 'analytics', 'Analytics/tracking detected', c.analytics.length ? 'PASS' : 'WARNING', 'info', c.analytics.length ? c.analytics.join(', ') : 'No known analytics scripts in served HTML (may be injected later)', 'Informational.', ''));
  out.push(chk(S, 'https', 'Served over HTTPS', c.http.https, 'critical', 'HTTPS', 'Final URL is HTTP', 'HTTP traffic is unencrypted.', 'Install a certificate and redirect HTTP to HTTPS.'));
  for (const [hd, name, sev] of [['strict-transport-security', 'HSTS', 'medium'], ['content-security-policy', 'Content-Security-Policy', 'medium'], ['x-content-type-options', 'X-Content-Type-Options', 'low'], ['referrer-policy', 'Referrer-Policy', 'low'], ['permissions-policy', 'Permissions-Policy', 'low']] as const)
    out.push(chk(S, hd, `${name} header`, !!h[hd], sev, `${hd}: ${String(h[hd]).slice(0, 80)}`, `${hd} header not present`, `Missing ${name} weakens browser-enforced protections.`, `Add the ${hd} response header.`, true));
  out.push(chk(S, 'xfo', 'Clickjacking protection', !!h['x-frame-options'] || /frame-ancestors/i.test(h['content-security-policy'] ?? ''), 'medium', 'X-Frame-Options or frame-ancestors present', 'Neither X-Frame-Options nor CSP frame-ancestors found', 'Page can be framed by other sites.', 'Add X-Frame-Options or CSP frame-ancestors.', true));
  out.push(chk(S, 'mixed', 'No mixed content', c.security.mixedContent === 0, 'high', 'No http:// references in HTML', `${c.security.mixedContent} http:// resource references in HTML`, 'Browsers block or warn on insecure subresources.', 'Change references to https://.'));
  out.push(chk('Mobile', 'viewport', 'Viewport meta tag', !!c.html.viewport, 'high', String(c.html.viewport), 'No viewport meta tag', 'Without it, mobile browsers render a desktop-width page.', 'Add <meta name="viewport" content="width=device-width, initial-scale=1">.'));
  out.push(chk('Domain & DNS', 'dns', 'Domain resolves', c.domain.dnsAddrs.length > 0, 'critical', c.domain.dnsAddrs.join(', '), 'DNS lookup returned no addresses', 'Domain must resolve.', 'Fix DNS records.'));
  if (c.http.https) out.push(c.domain.cert ? chk('Domain & DNS', 'cert', 'SSL certificate validity', c.domain.cert.daysLeft > 14, c.domain.cert.daysLeft < 0 ? 'critical' : 'high', `Expires ${c.domain.cert.validTo} (${c.domain.cert.daysLeft} days), issuer ${c.domain.cert.issuer}`, `Certificate expires in ${c.domain.cert.daysLeft} days`, 'Expired certs break HTTPS.', 'Renew the certificate; enable auto-renewal.') : F('Domain & DNS', 'cert', 'SSL certificate validity', 'INCOMPLETE', 'info', 'Certificate details could not be read', '', ''));
  out.push(F('Content Freshness', 'freshness', 'Last-modified signal', c.freshness.lastModified ? 'PASS' : 'INCOMPLETE', 'info', c.freshness.lastModified ? `Last modified: ${c.freshness.lastModified}` : 'No Last-Modified header or dateModified found', 'Informational only.', ''));
  const k = c.contact, hasC = k.mailto + k.tel + k.visibleEmails.length > 0;
  out.push(chk('Contact Information', 'contact', 'Contact details on page', hasC, 'low', `${k.mailto} mailto, ${k.tel} tel, ${k.visibleEmails.length} visible email(s)`, 'No mailto/tel links or visible emails found on this page', 'Not every page needs contact info; check site-wide.', 'Link to a contact page if appropriate.', true));
  const w = c.content.wordCount;
  out.push(chk('Content Quality', 'shell', 'Page has server-rendered content', w >= 100, 'high', `${w} words in served HTML`, `Only ${w} words in served HTML; content may be client-rendered`, 'Crawlers may see little content if it needs JavaScript. (Playwright rendering is not implemented in V1.)', 'Server-render or pre-render primary content.', w >= 20));
  out.push(chk('Content Quality', 'thin', 'Word count', w >= 300, 'low', `${w} words`, `${w} words`, 'Thin content can rank poorly for informational queries, but not every page needs length.', 'Add substantive content if the page targets informational search.', true));
  out.push(chk('Content Quality', 'heading-skips', 'Heading hierarchy', !c.html.headingSkips, 'low', 'No skipped heading levels', 'Heading levels are skipped (e.g. H2 → H4)', 'Skipped levels hurt outline navigation.', 'Use sequential heading levels.', true));
  out.push(chk('Links', 'links-empty', 'Links have text', c.links.emptyText === 0, 'medium', `${c.links.internal} internal, ${c.links.external} external links`, `${c.links.emptyText} links with no text or aria-label`, 'Unlabelled links are unusable for screen readers.', 'Add link text or aria-label.', true));
  return out;
}

const IMG_AUDITS = ['uses-optimized-images', 'modern-image-formats', 'offscreen-images', 'uses-responsive-images', 'efficient-animated-content', 'uses-webp-images'];
const MAP: Record<string, string> = { performance: 'Performance', accessibility: 'Accessibility', 'best-practices': 'Best Practices', seo: 'SEO' };
export function psiFindings(p: PsiResult, c: CrawlFacts | null): Finding[] {
  if (!p.ok) return [{ id: 'psi-error', category: 'Performance', title: 'PageSpeed audit incomplete', status: 'INCOMPLETE', severity: 'info', evidence: p.error ?? 'Data unavailable', explanation: '', recommendation: '', source: 'pagespeed' }];
  return (p.audits ?? []).flatMap((a): Finding[] => {
    const base = { id: `psi-${a.id}`, category: ['viewport', 'tap-targets', 'font-size'].includes(a.id) ? 'Mobile' : MAP[a.category] ?? a.category, title: `${a.title} (mobile)`, explanation: a.description, source: 'pagespeed' as const };
    if (a.mode === 'error') return [{ ...base, status: 'INCOMPLETE', severity: 'info', evidence: 'Lighthouse could not complete this audit', recommendation: '' }];
    if (IMG_AUDITS.includes(a.id) && c && c.images.count === 0) return [{ ...base, status: 'NOT_APPLICABLE', severity: 'info', evidence: 'No images were detected on the analyzed page.', recommendation: '' }];
    if (a.score == null || a.score >= 0.9 || !['numeric', 'binary', 'metricSavings'].includes(a.mode)) return [];
    return [{ ...base, status: a.score < 0.5 ? 'FAIL' : 'WARNING', severity: a.score < 0.5 ? 'high' : 'medium', evidence: `Lighthouse score ${Math.round(a.score * 100)}/100${a.displayValue ? `; ${a.displayValue}` : ''}${a.itemCount ? `; ${a.itemCount} item(s) flagged` : ''}${a.items?.length ? `; top flagged: ${a.items.join(' ;; ')}` : ''}`, recommendation: 'See Lighthouse guidance in the explanation above and address the flagged items.' }];
  });
}
